// Host test for JarvisEsp32/TuyaCodec.h + TuyaSession.h (Tuya LAN protocol 3.3/3.4/3.5).
// Runs on the Mac, no board needed — see tests/run_tuya_test.sh, or:
//   M=$(brew --prefix mbedtls@3)
//   c++ -std=c++17 -Wall -Wextra -I../JarvisEsp32 -I$M/include tuya_codec_test.cpp \
//       -L$M/lib -lmbedcrypto -o /tmp/tuya_test && /tmp/tuya_test
//
// Every byte string below was produced by tinytuya 1.20.0 (the reference implementation)
// under fixed keys, nonces, IVs, sequence numbers and timestamps, so a match means the
// board speaks exactly what tinytuya speaks. The generator script is not in the repo; the
// vectors are.
#include "TuyaCodec.h"
#include "TuyaSession.h"

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

using namespace jarvis::tuya;

static int failures = 0;
static int checks = 0;
#define CHECK(cond) do { ++checks; if (!(cond)) { std::printf("FAIL %s:%d  %s\n", __FILE__, __LINE__, #cond); ++failures; } } while (0)
#define CHECK_HEX(bytes, hex) do { ++checks; const std::string got_ = to_hex(bytes); if (got_ != (hex)) { \
    std::printf("FAIL %s:%d  %s\n  got  %s\n  want %s\n", __FILE__, __LINE__, #bytes, got_.c_str(), std::string(hex).c_str()); ++failures; } } while (0)

// ───────────────────────────── tinytuya vectors ─────────────────────────────
// Generated by gen_vectors.py with tinytuya 1.20.0. Do not edit by hand.
static const char* const kDevId = "bf1234567890abcdefgh";
static const char* const kLocalKey = "54713924785632216d4b3723704c347a";
static const char* const kClientNonce = "303132333435363738393a3b3c3d3e3f";
static const char* const kRemoteNonce = "f0efeeedecebeae9e8e7e6e5e4e3e2e1";
static const uint32_t kT = 1760000000;
static const char* const k33Query = "000055aa000000010000000a00000078f45b214e862d5a68e08844d2fe392181450469cd1caeeab3d0e6b071f0c61c0109c96c151d2a16e6d9af5bb683f6ef68d2a2f640db2aabf8179bd84bdac11c478a8f7e1fc22ba666515ce1312e9db092e886bcc83dd6a4bac44d8f93e88d6f44ec4b116149ed26f767c066a73b2ecde00f3881e40000aa55";
static const char* const k33Heartbeat = "000055aa000000020000000900000048f45b214e862d5a68e08844d2fe392181450469cd1caeeab3d0e6b071f0c61c0109c96c151d2a16e6d9af5bb683f6ef68b02a7122e3700082922ee3cb2d19731e22c38dad0000aa55";
static const char* const k33Control = "000055aa000000030000000700000087332e3300000000000000000000000097b31e3724a3539235ade948eba013f693ba7f0757dd76e9be6bdac665507a868c163cd337e1439371058d1d8e1474970d1e85fa995af692f531f02ba05c868b902b537c92f189ae8a5b83f35e4ef8871b8b2cd624e0cef18d750f81a6f6bcebceb06e8fff0db8589ed69e90bb553cc9a1dde0c00000aa55";
static const char* const k33Status = "000055aa00000007000000080000007b00000000332e3300000000000000000000000097b31e3724a3539235ade948eba013f693ba7f0757dd76e9be6bdac665507a86a366c3d3b682f6b58ad016ad819cc3eda50b3f3440533f0a15011e15a2ba79a8d256ef2833d78a48287ccdbdb77c6decff10043bc7cf79eb3006dbfa6f51a108fb2283540000aa55";
static const char* const k33StatusJson = "{\"devId\":\"bf1234567890abcdefgh\",\"dps\":{\"1\":true,\"101\":\"alarm\",\"102\":17},\"t\":1760000123}";
static const char* const k33QueryReply = "000055aa000000010000000a0000005c0000000097b31e3724a3539235ade948eba013f693ba7f0757dd76e9be6bdac665507a86a366c3d3b682f6b58ad016ad819cc3ed2088f5ad48e394ad5e610c4dcdd39d0c313619a0414fc65f26afae0382f43510f83d45ea0000aa55";
static const char* const k33QueryReplyJson = "{\"devId\":\"bf1234567890abcdefgh\",\"dps\":{\"1\":true,\"101\":\"normal\"}}";
static const char* const k33HeartbeatAck = "000055aa00000002000000090000000c00000000d00d1e480000aa55";
static const char* const k33WrongKeyReply = "000055aa000000010000000a0000005c00000000d32c9ca09f56eeb89adca9a4030dfd4e93f10347b6cceab389a4f1080f02c9c6dc5c371d683cc2f2e0d89926aeb6fe44a76119bfd9895272512b4cd15939d55d346bce0b8eed34da10f6a8fabb8444949eecdd9b0000aa55";
static const char* const k33Device22Query = "000055aa000000020000000d00000077332e3300000000000000000000000097b31e3724a3539235ade948eba013f693ba7f0757dd76e9be6bdac665507a868c163cd337e1439371058d1d8e1474970d1e85fa995af692f531f02ba05c868b902b537c92f189ae8a5b83f35e4ef88715130b687ef4bbf7da46e8453ae1353c2b02cb300000aa55";
static const char* const k33DataUnvalid = "000055aa000000010000000a0000002c0000000091f85383dfb170503f08850c3e5c741fcb4b3ef92a86e94ee6862c32f1a0059de738c9120000aa55";
static const char* const k34NegStart = "000055aa00000001000000030000004485b0436c951ec2a43012954c41a11b79313619a0414fc65f26afae0382f4351090f6fb87255de5d48a9c18bdbfac6961cad22d98819c5b0153ea46a68d2981710000aa55";
static const char* const k34NegResp = "000055aa00000064000000040000006800000000fdc6197fd1e351e8002046f043c706b48ad4416594304eb63d20f23db59e083cf661b3868bdc777102485bfbc7499e63313619a0414fc65f26afae0382f4351090dbb49c62d51ba38cb33a3a1dc70f346460f609446e79d694e62707dfd75da70000aa55";
static const char* const k34NegFinish = "000055aa0000000200000005000000543fcbef2306d83d2e4801e59a97c46298ad8a1ac5c2a4626b15fe65aabe632e05313619a0414fc65f26afae0382f4351063f4cf6cdaee905d177386edea3bb341a2a1f49a0784f7e6b8981f432976f8e60000aa55";
static const char* const k34SessionKey = "e9f84b84f5cf148f8cd83edcbb4b6925";
static const char* const k34Query = "000055aa000000030000001000000034b3dc09e594df19087c700187c0e02f1f720bdfca2e4c82d9834ced2c943e233c201bce282391c5cce39d106229cb21760000aa55";
static const char* const k34Heartbeat = "000055aa000000040000000900000064a04e8179b2813f4c7a9ca2e4a3ba487fd1ade0982b6292de17654d5ad0b2796d1f3d9549e12d72428e0ec901879296d80a0dbdeed62b5410446be091ca27f4436ac9be9d1085f4ea93f42d98f9b988b5d32a3cd50c0063887f53b8e25e395f790000aa55";
static const char* const k34Control = "000055aa000000050000000d000000847e66f6b4c93336678325cfdaf2b6d111abf299b4d2191789e39a3ce56143b558b92bf16eebce81509fc40d703efe6bb27f6d18c91288c9d8bb9e05d661b3dd3590e840da92dc1ed15b1527a840d0913851f88546aaf196640500e37043719dbc7b0dc1bb4a12833ef4c02dca28a92a6f34a38bba368bc7b401206c048b103e030000aa55";
static const char* const k34Status = "000055aa000000650000000800000088000000007e66f6b4c93336678325cfdaf2b6d111f4dc845b205c1d18a219879ffe39a2e155e1977b39e44fd213ac5c35eb8eae1461ccd6bb84b31b89a01b97199d6a61e7a3fe787ea522791605a2b82f74c7958fbf77a94ddb0954c5cfc180f509b21d2e4e8ac6d10326b1275ddde26f9082785dfc316d90bc7f4c41e98c094c044569550000aa55";
static const char* const k34StatusJson = "{\"protocol\":4,\"t\":1760000456,\"data\":{\"dps\":{\"1\":false,\"103\":\"door_open\"}}}";
static const char* const k34QueryAck = "000055aa000000660000001000000038000000006643547cf456f647fdada51bd498b4b349cfaa0b483c749007a5ece4e34611ff5e04b7923ccc32018d62a680a68a0a0e0000aa55";
static const char* const k34NegRespWrongKey = "000055aa00000064000000040000006800000000df72b5b1fc93391cc0e454e249ff1a43d0cac2c7cc949a18e7b5e262b3cb91d54e8a49a6a0194366833ec05c6073a0739d18550ffb09db671d69aea793f5d84db3ad34cf70e42dad14a0b8cf80c1253d10d7156d3359be61fe1fa7a8cc63bb410000aa55";
static const char* const k34NegRespBadNonceHmac = "000055aa00000064000000040000006800000000fdc6197fd1e351e8002046f043c706b480861d3b16a1ac97c089e08cc7c48da9a66525b647ace539f052760826293488313619a0414fc65f26afae0382f435106b947e9b36f8c21c06e712f779343da8abb8a273b8c77cde800ed59d68a107690000aa55";
static const char* const k35NegStart = "00006699000000000001000000030000002c000102030405060708090a0b2000a88276a8778b1cd0428e267ce9ea7ed885a99d73f0eaf7572e77278ad15600009966";
static const char* const k35NegResp = "000066990000000000c80000000400000050606162636465666768696a6b552f6f24e02b0a009fd7d65b0ffee775c9e657b232a3f92d5906953c8521401038d323b02764b43adb7a4a51c6a1a698f9709042fb369a477bee722f8f4c9506bbc6fc3600009966";
static const char* const k35NegFinish = "00006699000000000002000000050000003c101112131415161718191a1b74061413c852a23a6c5584bb4ec96cd8790285f007c5d0e11131b2fc488d6327f36b1f3b035358354de4a5701559f07600009966";
static const char* const k35SessionKey = "c2eb72f50e82b0d4b4905d6cf11f158e";
static const char* const k35Query = "00006699000000000003000000100000001e202122232425262728292a2b8ecd4f02aa13138106e399aa3381283f167b00009966";
static const char* const k35Heartbeat = "00006699000000000004000000090000005a303132333435363738393a3beb6e64e895b407b6ac3a014a65d6e3935eb030057abfca28460b66237b94bb41b50480f81cd9e74fb53a26eaaf4facb674d76f176bc57087d772ae50a0e73376151be71490c95aae1e3f8a5a1dc800009966";
static const char* const k35Control = "000066990000000000050000000d0000006e404142434445464748494a4b7a3d433670b0e40b252e37392164511b1a38241a39408ce18cd98cee39e9bfbf72b2df692f89367167abbcbf6e308359d688340febc943a7794b2db318b0f1badd8dac649cde4cecb7bcc73eb0a0e086876cb7f00db94b90f4a6a619dc18eb37cbd300009966";
static const char* const k35Status = "000066990000000000c90000000800000079707172737475767778797a7ba6023cbd610b3eead0fd68357a359dee12c6e4d12ec035a503d49923f7658b5f985ad90ae0fb3a436f229ac5840b5af7227e793130bc33816fd318d2349bdd2e942cfec970851d164cfecbb3aa2de56b3eb106d0cd0c557e9105072ffd69f477d2d30ff10d1dc09238896f613400009966";
static const char* const k35NegRespWrongKey = "000066990000000000c80000000400000050606162636465666768696a6b769c162ccf7c81d50b44571ae98f0646afecab21fb4e528d44de780a069f06dc38839632be730c9f68f97d8acf8d00693a1ee84c64cdeeda2f72d995d671964a620036a700009966";
static const char* const kUdpKey = "6c1ec8e2bb9bb59ab50b0daf649b410a";
static const char* const kBcast6667 = "000055aa00000000000000130000009c00000000d09766676f3369eb10b5e9f132fd802a23be2c4f88e5d7203f5814785738c202150931e65e45084a83b35b272a491c4aa41f010dca2abb30c50459a9f88024ffcb5924bb8792fe5eae7c9040e5921a98017f2170860421e6fc66f0a1ade138915fde850cd157270c5f3d1ab5ae90b300eabc77d2635fdf6c1afeaf031be1c97f6eda8eea40e93b1e3fc14a2570e182793bf047930000aa55";
static const char* const kBcast33Json = "{\"ip\":\"192.168.1.42\",\"gwId\":\"bf1234567890abcdefgh\",\"active\":2,\"ability\":0,\"mode\":0,\"encrypt\":true,\"productKey\":\"keyabc123\",\"version\":\"3.3\"}";
static const char* const kBcast7000 = "0000669900000000000000000023000000bd808182838485868788898a8b644dea7508e13b92a22b4ca6ef3846aae1ffbbaa01e3e35494b0fd734756914d0e03775b9a979acb583e6cca1e0de6f2f9812f4603bc9fea0ba446fe804b520f9f1b6df816fcba3ee07f29644172bcd5b0366d8d178bd084f1eef33cd9628dd264585e6639eef53a570d69c61ce8fe82246d11d75f7ff56ae196229942ef379756f33ce75bca92aeb6251d0e855cc12f6484b5cec54273bc4f6955146f196c5fa21736934c00b890f74025c35cdc3aedd400009966";
static const char* const kBcast7000NoRetcode = "0000669900000000000000000023000000bb909192939495969798999a9b249e18024ba09ed9d6468f8fb5c11bdd4a09ceb408f29bec1f99539341e00c2ecc523f84f7cc2335ba67eef52e1961b06255c95d1f478595f7437d032d5ddab9abbe342f596bd5402c5de2612a06f925d2f4e65d6edb9146e631552603a0f5d1f0cf025e4a0b172d49e4eed322a898810590d41a79411a26cf5947d96b8d750e0ebbd0259b3e502aea9db42206a6d5f9a66f746af6c1f55fa0f68339d8abf789dbcfeb5735cfda3e78099fe9688b9200009966";
static const char* const kBcast35Json = "{\"ip\":\"192.168.1.43\",\"gwId\":\"bf1234567890abcdefgh\",\"active\":2,\"ability\":0,\"encrypt\":true,\"productKey\":\"keyxyz789\",\"version\":\"3.5\",\"token\":true,\"wf_cfg\":true}";
static const char* const kBcast6666 = "000055aa000000000000001300000098000000007b226970223a223139322e3136382e312e3434222c2267774964223a226266313233343536373839306162636465666768222c22616374697665223a322c226162696c697479223a302c226d6f6465223a302c22656e6372797074223a66616c73652c2270726f647563744b6579223a226b65796f6c64303030222c2276657273696f6e223a22332e31227d3e7e62850000aa55";
static const char* const kBcast31Json = "{\"ip\":\"192.168.1.44\",\"gwId\":\"bf1234567890abcdefgh\",\"active\":2,\"ability\":0,\"mode\":0,\"encrypt\":false,\"productKey\":\"keyold000\",\"version\":\"3.1\"}";
static const char* const kDevinfoRequest = "000066990000000000000000002500000041a0a1a2a3a4a5a6a7a8a9aaab4a9f67e42f3456d975027943b65b590e86a758d8154fd07e7156d1f12265d47e31077fb73cafff8abeaa9618c0ec9ce9bbf0c5329b00009966";

// ───────────────────────────── helpers ─────────────────────────────

static Bytes from_hex(const char* hex) {
  Bytes out;
  const size_t n = std::strlen(hex);
  for (size_t i = 0; i + 1 < n; i += 2) {
    auto nib = [](char c) -> uint8_t { return c <= '9' ? c - '0' : (c | 0x20) - 'a' + 10; };
    out.push_back(static_cast<uint8_t>((nib(hex[i]) << 4) | nib(hex[i + 1])));
  }
  return out;
}

static std::string to_hex(const Bytes& b) {
  static const char* d = "0123456789abcdef";
  std::string s;
  for (uint8_t c : b) { s += d[c >> 4]; s += d[c & 15]; }
  return s;
}

// Same sequence the generator's fake os.urandom hands out: 16 bytes → the client nonce,
// the k-th 12-byte request → (k*16 + i).
static int g_iv_counter = 0;
static void fixed_rng(uint8_t* out, size_t n) {
  if (n == 16) {
    const Bytes nonce = from_hex(kClientNonce);
    std::memcpy(out, nonce.data(), 16);
  } else {
    for (size_t i = 0; i < n; ++i) out[i] = static_cast<uint8_t>(g_iv_counter * 16 + static_cast<int>(i));
    ++g_iv_counter;
  }
}

static Bytes take(Session& s) {
  Bytes out;
  s.take_output(out);
  return out;
}

static void feed(Session& s, const Bytes& b, uint32_t now) { s.feed(b.data(), b.size(), now, kT); }
static void feed_hex(Session& s, const char* hex, uint32_t now) { feed(s, from_hex(hex), now); }

static std::vector<Session::Report> reports(Session& s) {
  std::vector<Session::Report> out;
  Session::Report r;
  while (s.take_report(r)) out.push_back(r);
  return out;
}

static Bytes key() { return from_hex(kLocalKey); }

// ───────────────────────────── primitives ─────────────────────────────

static void test_primitives() {
  const char* check = "123456789";
  CHECK(crc32(reinterpret_cast<const uint8_t*>(check), 9) == 0xCBF43926u);
  CHECK(crc32(nullptr, 0) == 0);
  CHECK_HEX(Bytes(udp_key, udp_key + 16), kUdpKey);

  CHECK(parse_version("3.3") == Version::v33);
  CHECK(parse_version("3.4") == Version::v34);
  CHECK(parse_version("3.5") == Version::v35);
  CHECK(parse_version("auto") == Version::unknown);
  CHECK(parse_version("") == Version::unknown);
  CHECK(parse_version(nullptr) == Version::unknown);
  CHECK(parse_version("3.1") == Version::unknown);
  CHECK(std::strcmp(version_name(Version::v34), "3.4") == 0);
  CHECK(std::strcmp(version_name(Version::unknown), "auto") == 0);

  // PKCS7 round trip, and a block of garbage is rejected rather than "decrypted".
  const Bytes k = key();
  const std::string msg = "{\"dps\":{\"1\":true}}";
  const Bytes enc = ecb_encrypt_padded(k.data(), reinterpret_cast<const uint8_t*>(msg.data()), msg.size());
  CHECK(enc.size() == 32);
  Bytes dec;
  CHECK(ecb_decrypt_unpad(k.data(), enc.data(), enc.size(), dec));
  CHECK(std::string(dec.begin(), dec.end()) == msg);
  CHECK(!ecb_decrypt_unpad(k.data(), enc.data(), 15, dec));  // not a whole block
  // Last byte says "2 bytes of padding" but the byte before it disagrees.
  uint8_t block[16] = {'{', '}', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x01, 0x02};
  CHECK(aes_ecb(true, k.data(), block, 16, block));
  CHECK(!ecb_decrypt_unpad(k.data(), block, 16, dec));
}

// ───────────────────────────── 3.3 ─────────────────────────────

static void test_v33_encode() {
  const Bytes k = key();
  CHECK_HEX(encode_message(Version::v33, k.data(), 1, query_cmd(Version::v33, false),
                           query_json(Version::v33, kDevId, kT, false), nullptr), k33Query);
  CHECK_HEX(encode_message(Version::v33, k.data(), 2, cmd::heart_beat, heartbeat_json(kDevId), nullptr), k33Heartbeat);
  CHECK_HEX(encode_message(Version::v33, k.data(), 3, control_cmd(Version::v33),
                           control_json(Version::v33, kDevId, "{\"1\":true,\"101\":\"arm\"}", kT), nullptr), k33Control);
}

static void test_v33_session() {
  g_iv_counter = 0;
  const Bytes k = key();
  Session s(fixed_rng);
  s.start(Version::v33, kDevId, k.data(), 1000, kT);
  CHECK(s.phase() == Session::Phase::awaiting_first);
  CHECK_HEX(take(s), k33Query);
  CHECK(!s.ready());

  // Query reply, fed one byte at a time to exercise reassembly.
  const Bytes reply = from_hex(k33QueryReply);
  for (uint8_t b : reply) s.feed(&b, 1, 1100, kT);
  CHECK(s.ready());
  CHECK(s.phase() == Session::Phase::ready);
  auto r = reports(s);
  CHECK(r.size() == 1);
  if (r.size() == 1) {
    CHECK(r[0].cmd == cmd::dp_query);
    CHECK(r[0].json == k33QueryReplyJson);
    CHECK(r[0].query);  // answers the connect-time DP_QUERY
  }

  // Line noise ahead of a status push: resync on the prefix.
  Bytes noisy = {0x01, 0x02, 0x00, 0x00, 0x55};
  const Bytes status = from_hex(k33Status);
  noisy.insert(noisy.end(), status.begin(), status.end());
  feed(s, noisy, 1200);
  r = reports(s);
  CHECK(r.size() == 1);
  if (r.size() == 1) {
    CHECK(r[0].cmd == cmd::status);
    CHECK(r[0].json == k33StatusJson);
    CHECK(!r[0].query);  // an unsolicited push
  }

  // Two frames in one read.
  Bytes two = status;
  two.insert(two.end(), status.begin(), status.end());
  feed(s, two, 1300);
  CHECK(reports(s).size() == 2);

  // CRC mismatch: dropped, session survives.
  Bytes bad = status;
  bad[30] ^= 0x01;
  feed(s, bad, 1400);
  CHECK(reports(s).empty());
  CHECK(s.ready());
  CHECK(s.dropped_frames() == 1);

  // Heartbeat after 10 s (seq 2), then the control (seq 3): byte-exact with tinytuya.
  s.tick(11000, kT);
  CHECK_HEX(take(s), k33Heartbeat);
  CHECK(s.rtt_ms() == -1);
  feed_hex(s, k33HeartbeatAck, 11042);
  CHECK(s.rtt_ms() == 42);
  CHECK(s.control("{\"1\":true,\"101\":\"arm\"}", kT));
  CHECK_HEX(take(s), k33Control);

  // No traffic for 30 s: the link is dead.
  s.tick(41041, kT);
  CHECK(s.ready());
  take(s);  // heartbeats
  s.tick(41043, kT);
  CHECK(s.phase() == Session::Phase::failed);
  CHECK(s.failure() == Session::Failure::went_silent);
}

static void test_v33_failures() {
  const Bytes k = key();
  {  // Reply decrypts to garbage: the local key is wrong.
    Session s(fixed_rng);
    s.start(Version::v33, kDevId, k.data(), 0, kT);
    take(s);
    feed_hex(s, k33WrongKeyReply, 50);
    CHECK(s.phase() == Session::Phase::failed);
    CHECK(s.failure() == Session::Failure::key_rejected);
    CHECK(reports(s).empty());
  }
  {  // Silence: no answer.
    Session s(fixed_rng);
    s.start(Version::v33, kDevId, k.data(), 0, kT);
    s.tick(Session::answer_timeout_ms - 1, kT);
    CHECK(s.phase() == Session::Phase::awaiting_first);
    s.tick(Session::answer_timeout_ms + 1, kT);
    CHECK(s.failure() == Session::Failure::no_answer);
  }
  {  // A 3.5-framed answer to a 3.3 query: wrong version.
    Session s(fixed_rng);
    s.start(Version::v33, kDevId, k.data(), 0, kT);
    feed_hex(s, k35NegResp, 10);
    CHECK(s.failure() == Session::Failure::wrong_framing);
  }
  {  // "json obj data unvalid": key is right, device wants the device22 query form.
    Session s(fixed_rng);
    s.start(Version::v33, kDevId, k.data(), 0, kT);
    take(s);
    feed_hex(s, k33DataUnvalid, 10);
    CHECK(s.ready());
    CHECK_HEX(take(s), k33Device22Query);
    CHECK(reports(s).empty());
    CHECK(s.query(kT));  // later queries keep the device22 form (seq 3 now)
    CHECK(take(s).size() == from_hex(k33Device22Query).size());
  }
}

// ───────────────────────────── 3.4 ─────────────────────────────

static void test_v34() {
  g_iv_counter = 0;
  const Bytes k = key();
  Session s(fixed_rng);
  s.start(Version::v34, kDevId, k.data(), 0, kT);
  CHECK(s.phase() == Session::Phase::negotiating);
  CHECK_HEX(take(s), k34NegStart);

  feed_hex(s, k34NegResp, 30);
  CHECK(s.ready());
  CHECK_HEX(Bytes(s.session_key(), s.session_key() + 16), k34SessionKey);
  CHECK_HEX(take(s), std::string(k34NegFinish) + k34Query);  // finish, then the DP query

  s.tick(10000, kT);
  CHECK_HEX(take(s), k34Heartbeat);
  CHECK(s.control("{\"1\":true,\"101\":\"arm\"}", kT));
  CHECK_HEX(take(s), k34Control);

  feed_hex(s, k34Status, 10050);
  auto r = reports(s);
  CHECK(r.size() == 1);
  if (r.size() == 1) {
    CHECK(r[0].cmd == cmd::status);
    CHECK(r[0].json == k34StatusJson);
    CHECK(!r[0].query);  // the query went unanswered long ago; this is a push
  }
  // HMAC mismatch once established: dropped, not fatal.
  Bytes bad = from_hex(k34Status);
  bad[bad.size() - 10] ^= 0x80;
  feed(s, bad, 10060);
  CHECK(reports(s).empty());
  CHECK(s.ready());

  // Direct derivation matches too.
  uint8_t sk[16];
  derive_session_key(Version::v34, k.data(), from_hex(kClientNonce).data(), from_hex(kRemoteNonce).data(), sk);
  CHECK_HEX(Bytes(sk, sk + 16), k34SessionKey);
}

// A hub that acks DP_QUERY_NEW empty and then sends the snapshot as a STATUS: that
// STATUS is the query reply. A later STATUS is a push again.
static void test_v34_query_ack() {
  g_iv_counter = 0;
  const Bytes k = key();
  Session s(fixed_rng);
  s.start(Version::v34, kDevId, k.data(), 0, kT);
  feed_hex(s, k34NegResp, 30);
  CHECK(s.ready());
  take(s);
  feed_hex(s, k34QueryAck, 40);
  CHECK(reports(s).empty());
  CHECK(s.query_acks() == 1);
  feed_hex(s, k34Status, 60);
  auto r = reports(s);
  CHECK(r.size() == 1);
  if (r.size() == 1) CHECK(r[0].query);
  feed_hex(s, k34Status, 70);
  r = reports(s);
  CHECK(r.size() == 1);
  if (r.size() == 1) CHECK(!r[0].query);
  // Acked in time, but the STATUS comes after the window closed: a push.
  CHECK(s.query(kT));
  take(s);
  feed_hex(s, k34QueryAck, 75);
  feed_hex(s, k34Status, 70 + Session::answer_timeout_ms + 100);
  r = reports(s);
  CHECK(r.size() == 1);
  if (r.size() == 1) CHECK(!r[0].query);
  // An ack long after the query (outside the answer window) doesn't turn pushes into replies.
  CHECK(s.query(kT));
  take(s);
  feed_hex(s, k34QueryAck, 2 * Session::answer_timeout_ms + 1000);
  feed_hex(s, k34Status, 2 * Session::answer_timeout_ms + 1100);
  r = reports(s);
  CHECK(r.size() == 1);
  if (r.size() == 1) CHECK(!r[0].query);
}

static void test_v34_failures() {
  const Bytes k = key();
  {  // Device signs with another key: the frame HMAC can't match ours.
    Session s(fixed_rng);
    s.start(Version::v34, kDevId, k.data(), 0, kT);
    feed_hex(s, k34NegRespWrongKey, 10);
    CHECK(s.failure() == Session::Failure::key_rejected);
  }
  {  // Frame HMAC fine, but the nonce proof inside is wrong.
    Session s(fixed_rng);
    s.start(Version::v34, kDevId, k.data(), 0, kT);
    feed_hex(s, k34NegRespBadNonceHmac, 10);
    CHECK(s.failure() == Session::Failure::key_rejected);
  }
  {  // A CRC-trailed (3.3) frame back: wrong version, not a key problem.
    Session s(fixed_rng);
    s.start(Version::v34, kDevId, k.data(), 0, kT);
    feed_hex(s, k33QueryReply, 10);
    CHECK(s.failure() == Session::Failure::wrong_framing);
  }
  {
    Session s(fixed_rng);
    s.start(Version::v34, kDevId, k.data(), 0, kT);
    s.tick(Session::answer_timeout_ms + 1, kT);
    CHECK(s.failure() == Session::Failure::no_answer);
  }
}

// ───────────────────────────── 3.5 ─────────────────────────────

static void test_v35() {
  g_iv_counter = 0;
  const Bytes k = key();
  Session s(fixed_rng);
  s.start(Version::v35, kDevId, k.data(), 0, kT);
  CHECK_HEX(take(s), k35NegStart);

  feed_hex(s, k35NegResp, 25);
  CHECK(s.ready());
  CHECK_HEX(Bytes(s.session_key(), s.session_key() + 16), k35SessionKey);
  CHECK_HEX(take(s), std::string(k35NegFinish) + k35Query);

  s.tick(10000, kT);
  CHECK_HEX(take(s), k35Heartbeat);
  CHECK(s.control("{\"1\":true,\"101\":\"arm\"}", kT));
  CHECK_HEX(take(s), k35Control);

  feed_hex(s, k35Status, 10100);
  auto r = reports(s);
  CHECK(r.size() == 1);
  if (r.size() == 1) {
    CHECK(r[0].cmd == cmd::status);
    CHECK(r[0].json == k34StatusJson);  // same JSON body as the 3.4 vector
    CHECK(!r[0].query);
  }
  // Tag failure (ciphertext flipped): dropped.
  Bytes bad = from_hex(k35Status);
  bad[40] ^= 0x01;
  feed(s, bad, 10200);
  CHECK(reports(s).empty());
  CHECK(s.ready());
  // AAD covers the header: a rewritten sequence number fails too.
  bad = from_hex(k35Status);
  bad[9] ^= 0x01;
  feed(s, bad, 10300);
  CHECK(reports(s).empty());

  uint8_t sk[16];
  derive_session_key(Version::v35, k.data(), from_hex(kClientNonce).data(), from_hex(kRemoteNonce).data(), sk);
  CHECK_HEX(Bytes(sk, sk + 16), k35SessionKey);
}

static void test_v35_failures() {
  const Bytes k = key();
  {  // GCM tag under another key: the local key is wrong.
    Session s(fixed_rng);
    s.start(Version::v35, kDevId, k.data(), 0, kT);
    feed_hex(s, k35NegRespWrongKey, 10);
    CHECK(s.failure() == Session::Failure::key_rejected);
  }
  {  // 55AA back to a 6699 hello: the hub is older.
    Session s(fixed_rng);
    s.start(Version::v35, kDevId, k.data(), 0, kT);
    feed_hex(s, k34NegResp, 10);
    CHECK(s.failure() == Session::Failure::wrong_framing);
  }
  {  // Requests before the session is up are refused.
    Session s(fixed_rng);
    s.start(Version::v35, kDevId, k.data(), 0, kT);
    CHECK(!s.control("{\"1\":true}", kT));
    CHECK(!s.query(kT));
  }
  {  // A header claiming a giant payload is a protocol error, not a wait-forever.
    Session s(fixed_rng);
    s.start(Version::v35, kDevId, k.data(), 0, kT);
    const Bytes huge = from_hex("00006699000000000001000000080000ffff");
    feed(s, huge, 10);
    CHECK(s.failure() == Session::Failure::protocol);
  }
}

// ───────────────────────────── framing edge cases ─────────────────────────────

static void test_unpack_edges() {
  const Bytes k = key();
  const Bytes st = from_hex(k33Status);
  Frame f;
  size_t used = 0;
  CHECK(unpack(st.data(), 10, nullptr, false, f, used) == Unpack::need_more);
  CHECK(unpack(st.data(), st.size() - 1, nullptr, false, f, used) == Unpack::need_more);
  CHECK(unpack(st.data(), st.size(), nullptr, false, f, used) == Unpack::ok);
  CHECK(used == st.size());
  CHECK(f.cmd == cmd::status && f.seq == 7 && f.retcode == 0);
  // Declared length too short to hold retcode + CRC + suffix.
  const Bytes runt = from_hex("000055aa00000001000000080000000400000000");
  CHECK(unpack(runt.data(), runt.size(), nullptr, false, f, used) == Unpack::bad_length);
  const Bytes big = from_hex("000055aa0000000100000008000005a1");  // 1441 > 1440
  CHECK(unpack(big.data(), big.size(), nullptr, false, f, used) == Unpack::too_large);
  const Bytes junk = from_hex("0102030455aa");
  CHECK(unpack(junk.data(), junk.size(), nullptr, false, f, used) == Unpack::bad_prefix);
  CHECK(find_prefix(junk.data(), junk.size()) == junk.size() - 3);
  Bytes lead = {0xAA, 0xBB};
  lead.insert(lead.end(), st.begin(), st.end());
  CHECK(find_prefix(lead.data(), lead.size()) == 2);
}

// ───────────────────────────── discovery ─────────────────────────────

static void test_broadcasts() {
  std::string json;
  Bytes b = from_hex(kBcast6667);
  CHECK(decode_broadcast(b.data(), b.size(), json));
  CHECK(json == kBcast33Json);
  b = from_hex(kBcast7000);
  CHECK(decode_broadcast(b.data(), b.size(), json));
  CHECK(json == kBcast35Json);
  b = from_hex(kBcast7000NoRetcode);
  CHECK(decode_broadcast(b.data(), b.size(), json));
  CHECK(json == kBcast35Json);
  b = from_hex(kBcast6666);
  CHECK(decode_broadcast(b.data(), b.size(), json));
  CHECK(json == kBcast31Json);
  // Tampered GCM broadcast is refused.
  b = from_hex(kBcast7000);
  b[30] ^= 0x10;
  CHECK(!decode_broadcast(b.data(), b.size(), json));
  // Random bytes are refused.
  const Bytes junk(48, 0x5A);
  CHECK(!decode_broadcast(junk.data(), junk.size(), json));
  CHECK(!decode_broadcast(nullptr, 0, json));

  const Bytes iv = from_hex("a0a1a2a3a4a5a6a7a8a9aaab");
  CHECK_HEX(devinfo_request("192.168.1.50", iv.data()), kDevinfoRequest);
}

int main() {
  test_primitives();
  test_v33_encode();
  test_v33_session();
  test_v33_failures();
  test_v34();
  test_v34_query_ack();
  test_v34_failures();
  test_v35();
  test_v35_failures();
  test_unpack_edges();
  test_broadcasts();
  if (failures) {
    std::printf("%d of %d checks FAILED\n", failures, checks);
    return 1;
  }
  std::printf("tuya codec: all %d checks passed\n", checks);
  return 0;
}
