import Foundation

/// Every built-in effect and scene of the MELK controllers, by the Magic Lantern app's tabs.
/// Generated from `magiclantern-re/PROTOCOL.md` Appendix A (names verbatim from the app, its
/// spelling kept). Effects (tabs 0–7) are ids 0–212; scenes (MELK-OC / MELK-OT only) 1–28.
enum MelkCatalog {
    struct Item: Hashable, Identifiable {
        let id: UInt8
        let name: String
    }

    struct Tab: Identifiable {
        let id: Int
        let title: String
        let items: [Item]
    }

    static let effectTabs: [Tab] = [
        Tab(id: 0, title: "Basic", items: [
            Item(id: 0, name: "Auto Play"),
            Item(id: 1, name: "Magic Forward"),
            Item(id: 2, name: "Magic Back"),
            Item(id: 212, name: "7-Color Energy"),
            Item(id: 193, name: "7-Color Jump"),
            Item(id: 194, name: "R-G-B Jump"),
            Item(id: 195, name: "Y-C-P Jump"),
            Item(id: 196, name: "7-Color Strobe"),
            Item(id: 197, name: "R-G-B Strobe"),
            Item(id: 198, name: "Y-C-P Strobe"),
            Item(id: 199, name: "7-Color Gradual"),
            Item(id: 200, name: "R-Y Gradual"),
            Item(id: 201, name: "R-P Gradual"),
            Item(id: 202, name: "G-C Gradual"),
            Item(id: 203, name: "G-Y Gradual"),
            Item(id: 204, name: "B-P Gradual"),
            Item(id: 205, name: "Red Marquee"),
            Item(id: 206, name: "Green Marquee"),
            Item(id: 207, name: "Blue Marquee"),
            Item(id: 208, name: "Yellow Marquee"),
            Item(id: 209, name: "Cyan Marquee"),
            Item(id: 210, name: "Purple Marquee"),
            Item(id: 211, name: "White Marquee"),
            Item(id: 77, name: "7-Color Race"),
            Item(id: 78, name: "7-Color Race Back"),
            Item(id: 79, name: "R-G-B Race"),
            Item(id: 80, name: "R-G-B Race Back"),
            Item(id: 81, name: "Y-C-P Race"),
            Item(id: 82, name: "Y-C-P Race Back"),
            Item(id: 83, name: "7-Color Wave"),
            Item(id: 84, name: "7-Color Wave Back"),
            Item(id: 85, name: "R-G-B Wave"),
            Item(id: 86, name: "R-G-B Wave Back"),
            Item(id: 87, name: "Y-C-P Wave"),
            Item(id: 88, name: "Y-C-P Wave Back"),
            Item(id: 181, name: "7-Color Flush"),
            Item(id: 182, name: "7-Color Flush Back"),
            Item(id: 183, name: "R-G-B Flush"),
            Item(id: 184, name: "R-G-B Flush Back"),
            Item(id: 185, name: "Y-C-P Flush"),
            Item(id: 186, name: "Y-C-P Flush Back"),
            Item(id: 187, name: "7-Color Flush Close"),
            Item(id: 188, name: "7-Color Flush Open"),
            Item(id: 189, name: "R-G-B Flush Close"),
            Item(id: 190, name: "R-G-B Flush Open"),
            Item(id: 191, name: "Y-C-P Flush Close"),
            Item(id: 192, name: "Y-C-P Flush Open"),
        ]),
        Tab(id: 1, title: "Curtain", items: [
            Item(id: 57, name: "7-Color Close"),
            Item(id: 58, name: "7-Color Open"),
            Item(id: 59, name: "R-G-B Close"),
            Item(id: 60, name: "R-G-B Open"),
            Item(id: 61, name: "Y-C-P Close"),
            Item(id: 62, name: "Y-C-P Open"),
            Item(id: 63, name: "Red Close"),
            Item(id: 64, name: "Red Open"),
            Item(id: 65, name: "Green Close"),
            Item(id: 66, name: "Green Open"),
            Item(id: 67, name: "Blue Close"),
            Item(id: 68, name: "Blue Open"),
            Item(id: 69, name: "Yellow Close"),
            Item(id: 70, name: "Yellow Open"),
            Item(id: 71, name: "Cyan Close"),
            Item(id: 72, name: "Cyan Open"),
            Item(id: 73, name: "Purple Close"),
            Item(id: 74, name: "Purple Open"),
            Item(id: 75, name: "White Close"),
            Item(id: 76, name: "White Open"),
        ]),
        Tab(id: 2, title: "Trans", items: [
            Item(id: 3, name: "7-Color Trans"),
            Item(id: 4, name: "7-Color Trans Back"),
            Item(id: 5, name: "R-G-B Trans"),
            Item(id: 6, name: "R-G-B Trans Back"),
            Item(id: 7, name: "Y-C-P Trans"),
            Item(id: 8, name: "Y-C-P Trans Back"),
            Item(id: 9, name: "6-Color to Red"),
            Item(id: 10, name: "6-Color to Red Back"),
            Item(id: 11, name: "6-Color to Green"),
            Item(id: 12, name: "6-Color to Green Back"),
            Item(id: 13, name: "6-Color to Blue"),
            Item(id: 14, name: "6-Color to Blue Back"),
            Item(id: 15, name: "6-Color to Cyan"),
            Item(id: 16, name: "6-Color to Cyan Back"),
            Item(id: 17, name: "6-Color to Yellow"),
            Item(id: 18, name: "6-Color to Yellow Back"),
            Item(id: 19, name: "6-Color to Purple"),
            Item(id: 20, name: "6-Color to Purple Back"),
            Item(id: 21, name: "6-Color to White"),
            Item(id: 22, name: "6-Color to White Back"),
        ]),
        Tab(id: 3, title: "Water", items: [
            Item(id: 39, name: "7-Color Water"),
            Item(id: 40, name: "7-Color Water Back"),
            Item(id: 41, name: "R-G-B Water"),
            Item(id: 42, name: "R-G-B Water Back"),
            Item(id: 43, name: "Y-C-P Water"),
            Item(id: 44, name: "Y-C-P Water Back"),
            Item(id: 45, name: "R-G Water"),
            Item(id: 46, name: "R-G Water Back"),
            Item(id: 47, name: "G-B Water"),
            Item(id: 48, name: "G-B Water Back"),
            Item(id: 49, name: "Y-B Water"),
            Item(id: 50, name: "Y-B Water Back"),
            Item(id: 51, name: "Y-C Water"),
            Item(id: 52, name: "Y-C Water Back"),
            Item(id: 53, name: "C-P Water"),
            Item(id: 54, name: "C-P Water Back"),
            Item(id: 55, name: "White Water"),
            Item(id: 56, name: "White Water Back"),
        ]),
        Tab(id: 4, title: "Flow", items: [
            Item(id: 143, name: "W-R-W Flow"),
            Item(id: 144, name: "W-R-W Flow Back"),
            Item(id: 145, name: "W-G-W Flow"),
            Item(id: 146, name: "W-G-W Flow Back"),
            Item(id: 147, name: "W-B-W Flow"),
            Item(id: 148, name: "W-B-W Flow Back"),
            Item(id: 149, name: "W-Y-W Flow"),
            Item(id: 150, name: "W-Y-W Flow Back"),
            Item(id: 151, name: "W-C-W Flow"),
            Item(id: 152, name: "W-C-W Flow Back"),
            Item(id: 153, name: "W-P-W Flow"),
            Item(id: 154, name: "W-P-W Flow Back"),
            Item(id: 155, name: "R-W-R Flow"),
            Item(id: 156, name: "R-W-R Flow Back"),
            Item(id: 157, name: "G-W-G Flow"),
            Item(id: 158, name: "G-W-G Flow Back"),
            Item(id: 159, name: "B-W-B Flow"),
            Item(id: 160, name: "B-W-B Flow Back"),
            Item(id: 161, name: "Y-W-Y Flow"),
            Item(id: 162, name: "Y-W-Y Flow Back"),
            Item(id: 163, name: "C-W-C Flow"),
            Item(id: 164, name: "C-W-C Flow Back"),
            Item(id: 165, name: "P-W-P Flow"),
            Item(id: 166, name: "P-W-P Flow Back"),
        ]),
        Tab(id: 5, title: "Tail", items: [
            Item(id: 23, name: "7-Color Tail"),
            Item(id: 24, name: "7-Color Tail Back"),
            Item(id: 25, name: "Red Tail"),
            Item(id: 26, name: "Red Tail Back"),
            Item(id: 27, name: "Green Tail"),
            Item(id: 28, name: "Green Tail Back"),
            Item(id: 29, name: "Blue Tail"),
            Item(id: 30, name: "Blue Tail Back"),
            Item(id: 31, name: "Yellow Tail"),
            Item(id: 32, name: "Yellow Tail Back"),
            Item(id: 33, name: "Cyan Tail"),
            Item(id: 34, name: "Cyan Tail Back"),
            Item(id: 35, name: "Purple Tail"),
            Item(id: 36, name: "Purple Tail Back"),
            Item(id: 37, name: "White Tail"),
            Item(id: 38, name: "White Tail Back"),
        ]),
        Tab(id: 6, title: "Run", items: [
            Item(id: 89, name: "Red Running"),
            Item(id: 91, name: "Green Running"),
            Item(id: 93, name: "Blue Running"),
            Item(id: 95, name: "Yellow Running"),
            Item(id: 97, name: "Cyan Running"),
            Item(id: 99, name: "Purple Running"),
            Item(id: 101, name: "White Running"),
            Item(id: 103, name: "7-Color Running"),
            Item(id: 105, name: "R-G-B Running"),
            Item(id: 107, name: "Y-C-P Running"),
            Item(id: 109, name: "B-P-C-Y Running"),
            Item(id: 111, name: "B-G-C-Y Running"),
            Item(id: 113, name: "Red-Dot in White Running"),
            Item(id: 115, name: "Green-Dot in Red Running"),
            Item(id: 117, name: "Blue-Dot in Green Running"),
            Item(id: 119, name: "Yellow-Dot in Blue Running"),
            Item(id: 121, name: "Cyan-Dot in Yellow Running"),
            Item(id: 123, name: "Purple-Dot in Cyan Running"),
            Item(id: 125, name: "White-Dot in Purple Running"),
            Item(id: 127, name: "White-Dot in Red Running"),
            Item(id: 129, name: "7-Color in Red Running"),
            Item(id: 131, name: "7-Color in Green Running"),
            Item(id: 133, name: "7-Color in Blue Running"),
            Item(id: 135, name: "7-Color in Yellow Running"),
            Item(id: 137, name: "7-Color in Cyan Running"),
            Item(id: 139, name: "7-Color in Purple Running"),
            Item(id: 141, name: "7-Color in White Running"),
            Item(id: 167, name: "Green-Dot in Blue Running"),
            Item(id: 169, name: "Green-Dot in Red Running"),
            Item(id: 171, name: "Red-Dot in Blue Running"),
            Item(id: 173, name: "Cyan-Dot in Yellow Running"),
            Item(id: 175, name: "Yellow-Dot in Purple Running"),
            Item(id: 177, name: "White-Dot in Yelllow Running"),
            Item(id: 179, name: "Yellow-Dot in White Running"),
        ]),
        Tab(id: 7, title: "RunBack", items: [
            Item(id: 90, name: "Red Run Back"),
            Item(id: 92, name: "Green Run Back"),
            Item(id: 94, name: "Blue Run Back"),
            Item(id: 96, name: "Yellow Run Back"),
            Item(id: 98, name: "Cyan Run Back"),
            Item(id: 100, name: "Purple Run Back"),
            Item(id: 102, name: "White Run Back"),
            Item(id: 104, name: "7-Color Run Back"),
            Item(id: 106, name: "R-G-B Run Back"),
            Item(id: 108, name: "Y-C-P Run Back"),
            Item(id: 110, name: "B-P-C-Y Run Back"),
            Item(id: 112, name: "B-G-C-Y Run Back"),
            Item(id: 114, name: "Red-Dot in White Run Back"),
            Item(id: 116, name: "Green-Dot in Red Run Back"),
            Item(id: 118, name: "Blue-Dot in Green Run Back"),
            Item(id: 120, name: "Yellow-Dot in Blue Run Back"),
            Item(id: 122, name: "Cyan-Dot in Yellow Run Back"),
            Item(id: 124, name: "Purple-Dot in Cyan Run Back"),
            Item(id: 126, name: "White-Dot in Purple Run Back"),
            Item(id: 128, name: "White-Dot in Red Run Back"),
            Item(id: 130, name: "7-Color in Red Run Back"),
            Item(id: 132, name: "7-Color in Green Run Back"),
            Item(id: 134, name: "7-Color in Blue Run Back"),
            Item(id: 136, name: "7-Color in Yellow Run Back"),
            Item(id: 138, name: "7-Color in Cyan Run Back"),
            Item(id: 140, name: "7-Color in Purple Run Back"),
            Item(id: 142, name: "7-Color in White Run Back"),
            Item(id: 168, name: "Green-Dot in Blue Run Back"),
            Item(id: 170, name: "Green-Dot in Red Run Back"),
            Item(id: 172, name: "Red-Dot in Blue Run Back"),
            Item(id: 174, name: "Cyan-Dot in Yellow Run Back"),
            Item(id: 176, name: "Yellow-Dot in Purple Run Back"),
            Item(id: 178, name: "White-Dot in Yelllow Run Back"),
            Item(id: 180, name: "Yellow-Dot in White Run Back"),
        ]),
    ]

    static let scenes: [Item] = [
        Item(id: 1, name: "Sunrise"),
        Item(id: 2, name: "Sunset"),
        Item(id: 3, name: "Birthday"),
        Item(id: 4, name: "Candlelight"),
        Item(id: 5, name: "Fireworks"),
        Item(id: 6, name: "Party"),
        Item(id: 7, name: "Datiny"),
        Item(id: 8, name: "Starry sky"),
        Item(id: 9, name: "Romantic"),
        Item(id: 10, name: "Disco"),
        Item(id: 11, name: "Rainbow"),
        Item(id: 12, name: "Movie"),
        Item(id: 13, name: "Christmas"),
        Item(id: 14, name: "Flowing"),
        Item(id: 15, name: "Sleeping"),
        Item(id: 16, name: "Ocean"),
        Item(id: 17, name: "Forest"),
        Item(id: 18, name: "Reading"),
        Item(id: 19, name: "Working"),
        Item(id: 20, name: "Dazzle"),
        Item(id: 21, name: "Gentle"),
        Item(id: 22, name: "Wedding"),
        Item(id: 23, name: "Snow"),
        Item(id: 24, name: "Fire"),
        Item(id: 25, name: "Lightning"),
        Item(id: 26, name: "Valentine's Day"),
        Item(id: 27, name: "Hallowmas"),
        Item(id: 28, name: "Warnning"),
    ]

    static let effects: [Item] = effectTabs.flatMap(\.items)

    static func effect(id: UInt8) -> Item? { effects.first { $0.id == id } }

    /// An effect by its id or its name (any case, spaces/dashes ignored), for the agent.
    static func effect(named query: String) -> Item? {
        if let id = UInt8(query), let item = effect(id: id) { return item }
        let key = normalized(query)
        return effects.first { normalized($0.name) == key }
    }

    static func scene(named query: String) -> Item? {
        if let id = UInt8(query), let item = scenes.first(where: { $0.id == id }) { return item }
        let key = normalized(query)
        return scenes.first { normalized($0.name) == key }
    }

    private static func normalized(_ s: String) -> String {
        s.lowercased().filter { $0.isLetter || $0.isNumber }
    }

    /// The on-device microphone's eight effects (two rows of four in the app).
    static let micEffects = ["Energic", "Rhythm", "Spectrum", "Rolling", "Energic 2", "Rhythm 2", "Spectrum 2", "Rolling 2"]
}
