#!/usr/bin/env python3
"""Deterministic names for every still-unnamed function: <region prefix>_<behaviour>_<addr>."""
import re, os, sys, collections
sys.path.insert(0, os.path.dirname(__file__))
import names as N
RAW = os.path.join(os.path.dirname(__file__), '..', '..', 'decompiled', 'RT12_3.10.06.raw.c')
PREFIX = {"Boot":"boot","Hub":"hub","System":"sys","Factory":"factory","Time/date":"hist","LED":"led","BLE 16-byte":"ble_cmd",
 "BLE transport":"ble_tx","Big-data":"bigdata","Status LED":"pwr","Daily":"daily","Accelerometer":"accel","Gesture":"gesture",
 "I2C":"i2c","Heart-rate":"hr","Notification":"notif","BLE GATT":"gatt","Realtek":"sdk_gap","Math":"algo","Algorithm library state":"algo_sm",
 "Config":"cfg","Algorithm library (sleep":"algo_sleep","Pedometer":"pedo","SDK runtime":"rt"}
def region(addr):
    for lo,hi,lab in N.REGIONS:
        if lo<=addr<=hi:
            for k,v in PREFIX.items():
                if lab.startswith(k): return v
    return "rom" if addr < 0x800000 else "unk"
src=open(RAW).read()
known={f"FUN_{a:08x}" for a in list(N.FUNCS)+list(N.ROM)}
out={}
for f in re.split(r'\n(?=// =+\n// )',src)[1:]:
    m=re.match(r'// =+\n// (FUN_[0-9a-f]{8}) @ (0x[0-9a-f]+)\s+size=(\d+)',f)
    if not m or m.group(1) in known: continue
    addr=int(m.group(2),16); body=f.split('\n{',1)[-1]
    calls=set(re.findall(r'\b(\w+)\(',body))
    if 'tx_enqueue_packet' in calls: kind='send_pkt'
    elif 'FUN_00004926' in calls: kind='ipc'
    elif 'FUN_00013634' in calls: kind='timer_init'
    elif any(c in calls for c in ('FUN_00831b74','FUN_00831c6c','FUN_00831c06','FUN_00831cd2')): kind='reg_write'
    elif any(c in calls for c in ('FUN_00831b40','FUN_00831c38','FUN_00831bd2','FUN_00831c9e')): kind='reg_read'
    elif 'FUN_00005a06' in calls or 'FUN_00005aa8' in calls: kind='log'
    elif int(m.group(3))<=16 and not re.search(r'\bFUN_',body): kind='get' if 'return' in body and '=' not in body.split('return')[0] else 'set'
    elif 'FUN_0082744c' in calls: kind='hub_msg'
    elif 'FUN_00827128' in calls or 'FUN_00826898' in calls: kind='post_msg'
    elif re.search(r'\bswitch\(',body): kind='dispatch'
    elif not re.search(r'\bFUN_|\b[a-z_]+\(',body): kind='leaf'
    else: kind='fn'
    out[addr]=(f"{region(addr)}_{kind}_{addr:x}", f"Unread function; name is heuristic (subsystem + dominant behaviour + address).", "low")
with open(os.path.join(os.path.dirname(__file__),'names_agent.py'),'w') as fh:
    fh.write("# Generated by heuristic_names.py: deterministic placeholder names (subsystem_behaviour_addr) for unread functions.\nFUNCS_AGENT = {\n")
    for a in sorted(out): fh.write(f" {a:#010x}: {out[a]!r},\n")
    fh.write("}\n")
print(len(out),"heuristic names", collections.Counter(v[0].rsplit('_',2)[0] for v in out.values()).most_common(8))
