#!/usr/bin/env python3
"""Merge the per-batch agent JSON outputs into names_agent.py (hand names in names.py win)."""
import json, re, sys, os, glob
sys.path.insert(0, os.path.dirname(__file__))
import names as N
files = sys.argv[1:] or sorted(glob.glob(os.path.expanduser('~/agent_batches/out*.json')))
taken = {n for n, _ in N.FUNCS.values()} | {n for n, _ in N.ROM.values()} | set(N.GLOBALS.values())
hand = set(N.FUNCS) | set(N.ROM)
out, stats = {}, {"kept": 0, "renamed_dupe": 0, "skipped_hand": 0, "fixed_case": 0}
for fn in files:
    data = json.load(open(fn))
    for k, v in data.items():
        addr = int(k, 16)
        if addr in hand: stats["skipped_hand"] += 1; continue
        name = v.get("name", "").strip()
        desc = re.sub(r'\s+', ' ', v.get("desc", "")).strip()
        conf = v.get("confidence", "medium")
        fixed = re.sub(r'[^A-Za-z0-9_]', '_', name).strip('_').lower()
        if not fixed or fixed[0].isdigit(): fixed = f"fn_{fixed or addr:08x}"
        if fixed != name: stats["fixed_case"] += 1
        if fixed in taken: fixed = f"{fixed}_{addr:x}"; stats["renamed_dupe"] += 1
        taken.add(fixed)
        out[addr] = (fixed, desc, conf); stats["kept"] += 1
with open(os.path.join(os.path.dirname(__file__), 'names_agent.py'), 'w') as fh:
    fh.write("# Generated by merge_agent_names.py from Opus subagent output. Hand names in names.py override these.\n")
    fh.write("# addr: (name, description, confidence)\nFUNCS_AGENT = {\n")
    for addr in sorted(out):
        n, d, c = out[addr]
        fh.write(f" {addr:#010x}: ({n!r}, {d!r}, {c!r}),\n")
    fh.write("}\n")
print(stats, "->", len(out), "agent names")
